# Generated by Django 6.1 on 2026-08-26 10:28

import datarooms.tenancy.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0002_dataroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=datarooms.tenancy.storage.tenant_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='datarooms.dataroom')),
            ],
        ),
    ]
