# Generated by Django 6.1 on 2026-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0005_accessrestriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='theme',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
