# Generated by Django 6.1 on 2026-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0007_tag_template_office_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefolder',
            old_name='visible_to_roles',
            new_name='allowed_roles',
        ),
        migrations.AddField(
            model_name='accessrestriction',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templatefolder',
            name='user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
