# Generated by Django 6.1 on 2026-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0007_officemembership_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('color', models.CharField(default='brass', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dataroom',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='datarooms', to='datarooms.tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='datarooms.tag'),
        ),
    ]
