# Generated by Django 6.1 on 2026-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0008_rename_visible_to_roles_templatefolder_allowed_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre'), ('client', 'Client')], default='membre', max_length=20)),
                ('user_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='accessrestriction',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='access_restrictions', to='datarooms.group'),
        ),
        migrations.AddField(
            model_name='templatefolder',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='template_folders', to='datarooms.group'),
        ),
    ]
