# Generated by Django 6.1 on 2026-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0009_group_accessrestriction_groups_templatefolder_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='page_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
