"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h9=4e^uhvrvk_$p(f(8*l+ga-ffug(07k6076)41a#t+f_q&&1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.localhost']


# Application definition

CORS_ALLOWED_ORIGIN_REGEXES = [
    # Un seul label optionnel avant "localhost" ne suffit plus depuis le prototype
    # *.office.localhost (03/09/2026, voir CLAUDE.md) : un office créé en direct
    # depuis la console hyperadmin vit sous <nom>.office.localhost, deux labels
    # avant "localhost". Autorise désormais N labels, pas juste 0 ou 1.
    # Underscore ajouté le 04/09/2026 : Office.subdomain est un SlugField Django,
    # dont le validateur standard (validate_slug) accepte déjà lettres/chiffres/
    # tiret/underscore — un office créé en direct avec un underscore (ex.
    # "max_test") passait donc la validation du modèle mais ne matchait pas CE
    # regex, bloquant silencieusement tout appel API une fois sur l'écran de
    # connexion (même symptôme "Failed to fetch" que le blocage à N niveaux de
    # sous-domaine déjà corrigé) — confirmé par un test direct (préflight CORS
    # sans underscore accepté, avec underscore rejeté), voir docs/journal.md.
    r"^https://([a-z0-9_-]+\.)*localhost:5173$",
]
CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_extensions',
    'storages',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'datarooms',
]

# MFA (TOTP) — voir CLAUDE.md, section Architecture. Nom affiché dans l'appli
# d'authentification lors de l'enrôlement.
OTP_TOTP_ISSUER = 'Espace Notarial'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Chaque office garde sa PROPRE session (cookie scopé exactement à son hôte, sans
# attribut Domain). Domain=.localhost a été essayé et est rejeté par les navigateurs
# (localhost est traité comme un suffixe public par la Public Suffix List, RFC 6265bis
# anti-supercookie) — vérifié avec curl ET Chrome réel. Le passage d'un office à l'autre
# se fait donc par échange de ticket signé (datarooms/tenancy/sso.py), pas par un cookie
# partagé — voir CLAUDE.md, section "Architecture multi-tenant".
#
# CSRF_TRUSTED_ORIGINS est nécessaire dès qu'un POST authentifié par session (ex:
# /api/sso/issue/) est fait cross-port depuis le frontend Vite (:5173) vers le backend
# Django (:8000) : Origin != Host de la requête sinon rejeté par CsrfViewMiddleware.
CSRF_TRUSTED_ORIGINS = ['https://*.localhost:5173']

# Les deux serveurs de dev tournent exclusivement en HTTPS (certificats mkcert, voir
# CLAUDE.md) : cookies Secure activés. Si jamais quelqu'un relance `runserver` en HTTP
# nu par erreur, les cookies cessent d'être transmis — c'est le signal qu'il faut
# repasser par `runserver_plus --cert-file --key-file`.
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'datarooms.tenancy.middleware.TenantResolutionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Une base SQLite physique distincte par office (tenant), enregistrée dynamiquement
# via datarooms.tenancy.registry.ensure_tenant_registered — voir CLAUDE.md, section
# "Architecture multi-tenant".
TENANT_DB_DIR = BASE_DIR / 'tenants'

DATABASE_ROUTERS = ['datarooms.tenancy.router.TenantRouter']


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Fichiers uploadés (Document) — stockage S3-compatible via MinIO local (remplace le
# stockage disque du chantier précédent). Le préfixe par tenant est calculé par
# datarooms.tenancy.storage.tenant_document_path, inchangé : c'est tout l'intérêt de
# l'abstraction FileField standard, le nom relatif ne dépend pas du backend.
# Bucket à créer une fois (voir CLAUDE.md, Commandes) — ni MinIO ni S3 ne le créent
# automatiquement.
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": "espace-notarial-documents",
            "endpoint_url": "http://localhost:9000",
            "access_key": "minioadmin",
            "secret_key": "minioadmin",
            "region_name": "us-east-1",  # ignoré par MinIO mais requis par boto3
            "addressing_style": "path",  # MinIO sans DNS wildcard : path-style requis
            "use_ssl": False,  # MinIO local sans TLS propre à lui (indépendant du HTTPS Vite/Django)
            "default_acl": None,  # pas d'en-tête ACL — MinIO le rejette souvent
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
